[package]
name = "typst-jp-conf-template"
version = "0.0.2"
compiler = "0.12.0"
entrypoint = "libs/mscs/lib.typ"
repository = "https://github.com/kimushun1101/typst-jp-conf-template"
authors = ["Shunsuke Kimura <https://github.com/kimushun1101>", "ささくらり <https://github.com/m-tsuru>"]
license = "MIT-0"
description = "Typst で日本語論文を書くときのテンプレート "
keywords = ["japanese", "conference"]
categories = ["paper"]

[template]
path = ""
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
