name: "Typst common steps"

description: "Composite action providing checkout, cache, fonts and Typst setup. Optionally runs a compile command."

inputs:
  input_file:
    description: "The input file to typst compile."
    required: true
    default: 'tests/test-make-doc.typ'
  output_file:
    description: "The output file from typst compile."
    required: false
    default: '${{ github.event.repository.name }}-${{ github.ref_name }}.pdf'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache apt debs (fonts)
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives/*.deb
        key: apt-${{ runner.os }}

    - name: Install fonts
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fonts-noto \
          fonts-noto-cjk \
          fonts-noto-cjk-extra

    - name: Setup Typst
      uses: typst-community/setup-typst@v3

    - name: Run compile command
      shell: bash
      run: typst compile --root . ${{ inputs.input_file }} ${{ inputs.output_file }}
